import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { API_URL } from '../config';
import { Bell, ChevronRight, DollarSign, Calendar, AlertCircle, CheckCircle, Trash2, Check, Loader2, Repeat2 } from 'lucide-react';

const API=`${API_URL}/api/tutor/notifications`;
const auth=()=>{const token=localStorage.getItem('student_token');return token?{headers:{Authorization:`Bearer ${token}`}}:{};};
const meta={payment:{label:'การเงิน',Icon:DollarSign,bg:'bg-green-100',color:'text-green-600'},schedule:{label:'ตารางสอน',Icon:Calendar,bg:'bg-orange-100',color:'text-orange-600'},alert:{label:'ต้องจัดการ',Icon:AlertCircle,bg:'bg-red-100',color:'text-red-600'},success:{label:'สำเร็จ',Icon:CheckCircle,bg:'bg-emerald-100',color:'text-emerald-600'},release:{label:'คาบสอนแทน',Icon:Repeat2,bg:'bg-blue-100',color:'text-blue-600'}};
function ago(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return'—';const s=Math.max(0,Math.floor((Date.now()-d)/1000));if(s<60)return'เมื่อสักครู่';if(s<3600)return`${Math.floor(s/60)} นาทีที่แล้ว`;if(s<86400)return`${Math.floor(s/3600)} ชั่วโมงที่แล้ว`;if(s<604800)return`${Math.floor(s/86400)} วันที่แล้ว`;return d.toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'});}

export default function TutorNotifications(){
  const navigate=useNavigate();
  const [filter,setFilter]=useState('all');const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const {data}=await axios.get(API,auth());setItems(Array.isArray(data.items)?data.items:[]);}catch(err){setError(err.response?.data?.message||'โหลดการแจ้งเตือนไม่สำเร็จ');}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const unread=items.filter(x=>!x.isRead).length;
  const filtered=useMemo(()=>items.filter(x=>filter==='all'?true:filter==='unread'?!x.isRead:filter==='read'?x.isRead:x.type===filter),[items,filter]);
  const types=[...new Set(items.map(x=>x.type))];
  const mark=async id=>{setBusy(id);try{await axios.patch(`${API}/${encodeURIComponent(id)}/read`,{},auth());setItems(xs=>xs.map(x=>x.id===id?{...x,isRead:true}:x));}catch(err){setError(err.response?.data?.message||'บันทึกสถานะไม่สำเร็จ');}finally{setBusy('');}};
  const markAll=async()=>{setBusy('all');try{await axios.patch(`${API}/read-all`,{},auth());setItems(xs=>xs.map(x=>({...x,isRead:true})));}catch(err){setError(err.response?.data?.message||'บันทึกสถานะไม่สำเร็จ');}finally{setBusy('');}};
  const dismiss=async id=>{setBusy(id);try{await axios.delete(`${API}/${encodeURIComponent(id)}`,auth());setItems(xs=>xs.filter(x=>x.id!==id));}catch(err){setError(err.response?.data?.message||'ซ่อนรายการไม่สำเร็จ');}finally{setBusy('');}};
  const act=async item=>{if(!item.isRead)await mark(item.id);if(item.link)navigate(item.link);};

  return <div className="min-h-screen space-y-6 mt-[90px]"><div className="mx-auto">
    <div className="mb-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h1 className="text-3xl font-bold text-neutral-900 flex items-center gap-3"><Bell className="h-8 w-8 text-orange-600"/>การแจ้งเตือน</h1><p className="mt-2 text-base text-neutral-500">ข้อมูลจริงสำหรับงานสอนของคุณ · ยังไม่ได้อ่าน {unread} รายการ</p></div>{unread>0&&<button onClick={markAll} disabled={busy==='all'} className="self-end flex items-center gap-2 px-5 py-3 bg-orange-500 text-white rounded-xl hover:bg-orange-600 font-semibold disabled:opacity-60"><Check className="h-5 w-5"/>อ่านทั้งหมด</button>}</div>
    {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 flex justify-between"><span>{error}</span><button onClick={load} className="font-bold underline">ลองใหม่</button></div>}
    <div className="bg-white rounded-2xl border-2 border-neutral-200 p-2 mb-6"><div className="flex flex-wrap gap-2"><button onClick={()=>setFilter('all')} className={`px-4 py-2 rounded-lg text-sm font-medium ${filter==='all'?'bg-orange-500 text-white':'text-neutral-600 hover:bg-neutral-100'}`}>ทั้งหมด ({items.length})</button><button onClick={()=>setFilter('unread')} className={`px-4 py-2 rounded-lg text-sm font-medium ${filter==='unread'?'bg-orange-500 text-white':'text-neutral-600 hover:bg-neutral-100'}`}>ยังไม่ได้อ่าน ({unread})</button>{types.map(type=><button key={type} onClick={()=>setFilter(type)} className={`px-4 py-2 rounded-lg text-sm font-medium ${filter===type?'bg-orange-500 text-white':'text-neutral-600 hover:bg-neutral-100'}`}>{meta[type]?.label||type}</button>)}</div></div>
    {loading?<div className="bg-white rounded-2xl border-2 border-neutral-200 p-14 text-center"><Loader2 className="h-8 w-8 animate-spin text-orange-500 mx-auto mb-3"/><p className="text-neutral-500">กำลังโหลดงานของคุณ...</p></div>:filtered.length===0?<div className="bg-white rounded-2xl border-2 border-neutral-200 p-12 text-center"><Bell className="h-16 w-16 text-neutral-300 mx-auto mb-4"/><p className="font-semibold text-neutral-700">ไม่มีการแจ้งเตือน</p><p className="text-sm text-neutral-400 mt-1">หากไม่มีงานค้าง หน้านี้ว่างได้เป็นปกติ</p></div>:<div className="space-y-4">{filtered.map(item=>{const m=meta[item.type]||{label:item.type,Icon:Bell,bg:'bg-neutral-100',color:'text-neutral-600'};return <div key={item.id} className={`bg-white rounded-2xl border-2 hover:border-orange-300 overflow-hidden ${item.isRead?'border-neutral-200':'border-orange-200 bg-orange-50/30'}`}><div className="relative p-6 flex gap-4"><div className={`p-3 rounded-xl ${m.bg} shrink-0 h-fit`}><m.Icon className={`h-6 w-6 ${m.color}`}/></div><div className="flex-1 min-w-0 md:pr-56"><div className="flex flex-wrap items-center gap-2 mb-2"><h3 className="text-lg font-bold text-neutral-900">{item.title}{!item.isRead&&<span className="ml-2 inline-block w-2 h-2 bg-orange-500 rounded-full"/>}</h3><span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-semibold text-neutral-600">{m.label||item.type}</span></div><p className="text-base leading-7 text-neutral-700">{item.message}</p><span className="mt-2 block text-sm text-neutral-400">{ago(item.createdAt)}</span><div className="mt-4 flex flex-wrap gap-2 md:absolute md:right-5 md:top-5 md:mt-0 md:w-48 md:flex-col">{item.link&&<button onClick={()=>act(item)} className="flex justify-center items-center gap-1 px-4 py-2.5 text-sm bg-orange-500 text-white rounded-xl hover:bg-orange-600 font-semibold">{item.actionLabel||'ดูรายละเอียด'}<ChevronRight className="h-4 w-4"/></button>}{!item.isRead&&<button disabled={busy===item.id} onClick={()=>mark(item.id)} className="flex justify-center items-center gap-1 px-4 py-2.5 text-sm bg-orange-100 text-orange-700 rounded-xl hover:bg-orange-200 font-semibold"><Check className="h-4 w-4"/>อ่านแล้ว</button>}<button disabled={busy===item.id} onClick={()=>dismiss(item.id)} className="flex justify-center items-center gap-1 px-4 py-2.5 text-sm bg-red-50 text-red-700 rounded-xl hover:bg-red-100 font-semibold"><Trash2 className="h-4 w-4"/>ซ่อนรายการ</button></div></div></div></div>;})}</div>}
  </div></div>;
}
