const time = seconds => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`;
export default function TutorVideoReplayReport({ data, onSeek }) {
  if (!data?.heatmap?.length) return <p className="py-8 text-center text-sm text-slate-500">ยังไม่มีข้อมูลการรับชมสำหรับวิเคราะห์การดูซ้ำ</p>;
  const peak = Math.max(1, ...data.heatmap.map(segment => segment.replayCount));
  const ranked = [...data.heatmap].filter(segment => segment.replayCount > 0).sort((a, b) => b.replayCount - a.replayCount).slice(0, 5);
  return <div className="space-y-4 text-sm">
    <p className="text-xs leading-relaxed text-slate-500">แต่ละช่องคือช่วง {data.segmentSeconds} วินาที สีเข้มแสดงช่วงที่มีการรับชมซ้ำมาก กดเพื่อเลื่อนไปดูเนื้อหา การดูซ้ำอาจเป็นการทบทวนหรือกลับมาดูในรอบใหม่ จึงควรพิจารณาร่วมกับผลคำตอบ</p>
    <div className="grid grid-cols-5 gap-2 sm:grid-cols-6">{data.heatmap.map(segment => <button type="button" key={segment.segmentIndex} onClick={() => onSeek(segment.startSecond)} title={`ผู้ชม ${segment.viewerCount} คน · รับชม ${segment.playCount} ครั้ง · ซ้ำ ${segment.replayCount} ครั้ง`} style={{ backgroundColor: `rgba(249,115,22,${0.08 + 0.65 * segment.replayCount / peak})` }} className="rounded-lg p-2 text-center text-xs text-slate-900"><span className="block font-bold">{time(segment.startSecond)}</span><span className="block mt-1">ซ้ำ {segment.replayCount}</span></button>)}</div>
    <div><h4 className="font-bold text-slate-800">ช่วงที่ดูซ้ำมากที่สุด</h4>{ranked.length ? ranked.map(segment => <button type="button" key={segment.segmentIndex} onClick={() => onSeek(segment.startSecond)} className="mt-2 flex w-full justify-between rounded-xl bg-orange-50 p-3 text-xs text-orange-700"><span>{time(segment.startSecond)}–{time(segment.startSecond + data.segmentSeconds)}</span><span>ซ้ำ {segment.replayCount} ครั้ง · {segment.viewerCount} คน</span></button>) : <p className="mt-2 text-xs text-slate-500">ยังไม่พบการดูซ้ำ</p>}</div>
    {!!data.questions?.length && <div><h4 className="font-bold text-slate-800">ผลคำตอบและจุดที่หยุดดู</h4><p className="mt-1 text-xs text-slate-500">จำนวนรอบที่จบใกล้คำถามยังไม่ยืนยันว่าผู้เรียนเลิกเรียน หรือไม่เข้าใจ</p>{data.questions.map(question => <div key={question.questionId} className="mt-2 rounded-xl bg-slate-50 p-3"><button type="button" onClick={() => onSeek(question.timestampMs / 1000)} className="text-xs font-bold text-orange-600">{time(question.timestampMs / 1000)}</button><p className="mt-1 text-sm font-medium">{question.text}</p><p className="mt-2 text-xs text-slate-600">{question.answeredCount ? `ตอบผิด ${question.errorRate}% จาก ${question.answeredCount} คำตอบ` : "ยังไม่มีคำตอบ"} · จบรอบใกล้จุดนี้ {question.dropOffNearQuestion} รอบ</p></div>)}</div>}
  </div>;
}
