export const rooms = [{
    "id": 1,
    "name": "ห้อง 1",
    "floor": 1,
    "capacity": 8,
    "status": "พร้อมใช้งาน",
    "facilities": [{
      "Room_Facilities_Id": 120001,
      "FacilitiesId": 5,
      "Facilities_Name": "กระดาน",
      "Quantity": 2
    }, {
      "Room_Facilities_Id": 120003,
      "FacilitiesId": 3,
      "Facilities_Name": "ทีวี",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 120005,
      "FacilitiesId": 1,
      "Facilities_Name": "เครื่องปรับอากาศ",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 120007,
      "FacilitiesId": 30001,
      "Facilities_Name": "โปรเจกเตอร์",
      "Quantity": 1
    }]
  }, {
    "id": 2,
    "name": "ห้อง 2",
    "floor": 2,
    "capacity": 22,
    "status": "พร้อมใช้งาน",
    "facilities": [{
      "Room_Facilities_Id": 90001,
      "FacilitiesId": 5,
      "Facilities_Name": "กระดาน",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 90003,
      "FacilitiesId": 3,
      "Facilities_Name": "ทีวี",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 90009,
      "FacilitiesId": 90001,
      "Facilities_Name": "ลำโพง",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 90005,
      "FacilitiesId": 1,
      "Facilities_Name": "เครื่องปรับอากาศ",
      "Quantity": 2
    }, {
      "Room_Facilities_Id": 90007,
      "FacilitiesId": 30001,
      "Facilities_Name": "โปรเจกเตอร์",
      "Quantity": 1
    }]
  }, {
    "id": 3,
    "name": "ห้อง 3",
    "floor": 2,
    "capacity": 12,
    "status": "พร้อมใช้งาน",
    "facilities": [{
      "Room_Facilities_Id": 60001,
      "FacilitiesId": 5,
      "Facilities_Name": "กระดาน",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60003,
      "FacilitiesId": 3,
      "Facilities_Name": "ทีวี",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60009,
      "FacilitiesId": 60001,
      "Facilities_Name": "พัดลม",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60005,
      "FacilitiesId": 1,
      "Facilities_Name": "เครื่องปรับอากาศ",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60007,
      "FacilitiesId": 30001,
      "Facilities_Name": "โปรเจกเตอร์",
      "Quantity": 1
    }]
  }, {
    "id": 30002,
    "name": "ห้อง 4",
    "floor": 2,
    "capacity": 12,
    "status": "พร้อมใช้งาน",
    "facilities": [{
      "Room_Facilities_Id": 60011,
      "FacilitiesId": 5,
      "Facilities_Name": "กระดาน",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60013,
      "FacilitiesId": 3,
      "Facilities_Name": "ทีวี",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60019,
      "FacilitiesId": 60001,
      "Facilities_Name": "พัดลม",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60015,
      "FacilitiesId": 1,
      "Facilities_Name": "เครื่องปรับอากาศ",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 60017,
      "FacilitiesId": 30001,
      "Facilities_Name": "โปรเจกเตอร์",
      "Quantity": 1
    }]
  }, {
    "id": 5,
    "name": "ห้อง 5",
    "floor": 3,
    "capacity": 12,
    "status": "พร้อมใช้งาน",
    "facilities": [{
      "Room_Facilities_Id": 30033,
      "FacilitiesId": 5,
      "Facilities_Name": "กระดาน",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 30035,
      "FacilitiesId": 3,
      "Facilities_Name": "ทีวี",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 30037,
      "FacilitiesId": 1,
      "Facilities_Name": "เครื่องปรับอากาศ",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 30039,
      "FacilitiesId": 30001,
      "Facilities_Name": "โปรเจกเตอร์",
      "Quantity": 1
    }]
  }, {
    "id": 7,
    "name": "ห้อง 6",
    "floor": 3,
    "capacity": 12,
    "status": "พร้อมใช้งาน",
    "facilities": []
  }, {
    "id": 8,
    "name": "ห้อง 7",
    "floor": 3,
    "capacity": 6,
    "status": "พร้อมใช้งาน",
    "facilities": [{
      "Room_Facilities_Id": 30041,
      "FacilitiesId": 5,
      "Facilities_Name": "กระดาน",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 30043,
      "FacilitiesId": 3,
      "Facilities_Name": "ทีวี",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 30045,
      "FacilitiesId": 1,
      "Facilities_Name": "เครื่องปรับอากาศ",
      "Quantity": 1
    }, {
      "Room_Facilities_Id": 30047,
      "FacilitiesId": 30001,
      "Facilities_Name": "โปรเจกเตอร์",
      "Quantity": 1
    }]
  }];
